name: eduflex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  file_picker: ^5.2.5
  video_player: ^2.9.5
  url_launcher: ^6.3.1
  flutter_animate: ^4.5.2
  flutter_pdfview: ^1.4.0
  path_provider: ^2.1.5
  flutter_cached_pdfview: ^0.4.3
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  supabase_flutter: ^2.8.4
  intl: ^0.20.2
  animate_do: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  